- name: Deploy to server
  hosts: test-servers
  gather_facts: False # Fails without this because Python 2 is missing

  tasks:
  - name: Update packages
    apt: update_cache=yes
    become: true
    become_user: root
    
    # No Python 2 in Ubuntu 16.04, but Ansible needs it.
  - name: Install Python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    become: true
    become_user: root

    # To prevent "ImportError: No module named pkg_resources
  - name: Install Python setuptools
    raw: wget https://bootstrap.pypa.io/ez_setup.py -O - | python
    become: true
    become_user: root

  - name: Install Ansible Docker module
    raw: pip install 'docker-py>=1.7.0'
    become: true
    become_user: root

  - name: Install Docker
    script: scripts/install_docker.sh
    become: true
    become_user: root

  - name: Stop & remove app container
    docker:
      name: voimala-app
      image: jarzka/voimala.org-app
      state: absent

  - name: Stop & remove nginx container
    docker:
      name: voimala-nginx
      image: jarzka/voimala.org-nginx
      state: absent

  - name: Remove old nginx image
    docker_image:
      state: absent
      name: jarzka/voimala.org-nginx

  - name: Remove old app image
    docker_image:
      state: absent
      name: jarzka/voimala.org-app

  - name: Download app image
    raw: docker pull jarzka/voimala.org-app

  - name: Download nginx image
    raw: docker pull jarzka/voimala.org-nginx

  - name: Copy Docker composite file
    copy: src=docker/voimala.org/docker-compose.yml dest=~/docker-compose.yml

  - name: Run Docker composite file
    raw: cd ~ && docker-compose up -d
